version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.10.5
    
    working_directory: ~/repo
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "requirements.txt" }}
          - v2-dependencies-

      - run:
          name: install dependencies
          command: |
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            pip install onnxruntime-training
#            python -c "from onnxruntime.training.ortmodule.torch_cpp_extensions import install as ortmodule_install;ortmodule_install.build_torch_cpp_extensions()"

      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: compile and build
          command: |
            python setup.py build_ext --inplace

      - run:
          name: flake8
          command: |
            python -m flake8 --ignore=E501 deeponnxcustom
            python -m flake8 --ignore=E501 _doc/examples

      - run:
          name: run tests
          command: |
            python setup.py unittests

      - run:
          name: wheel
          command: |
            python setup.py bdist_wheel
            cp dist/*.whl test-reports

      - run:
          name: check speed
          command: |
            python -m deeponnxcustom check

      - store_artifacts:
          path: test-reports
          destination: test-reports
